### ISSUE TITLE
BkgVideoPOTVL missing opacity value

### ISSUE THREAD

**Issue by matzrm** [carlonluca/Fall#1]
Just to follow-up and resolve the exchange we had on your blog, regarding why in my case omxplayer was not visible under the Qt/QML application. 

The answer was right in front of my eyes: inside the Rectangle defined in ` BkgVideoPOTVL.qml` the `opacity` property is missing.

Thank you for your work.

**Comment by carlonluca** [comment]
Hello,
the Video element is above the Rectangle, and I think it should therefore be visible. If this is what you are seeing, something else may be wrong. At the moment I do not have a setup to debug though.

**Comment by matzrm** [comment]
The video layer is above but omxplayer is started with layer -128  and my
framebuffer (so also my qt application) is at -127. If I not set opacity
less then 1 I can’t see the video under the application.

**Comment by carlonluca** [comment]
This is correct. omxplayer must be below Qt. POTVL should show or hide it properly without your intervention.

**Comment by carlonluca** [comment]
A possible reason for what you are seeing is that you are not using the bundled omxplayer: https://github.com/carlonluca/pot/tree/master/piomxtextures_videolayer/omxplayer/buster/omxplayer-dist/usr.

That omxplayer binary sends additional dbus signals that are used to better sync with the UI.

**Comment by matzrm** [comment]
Yes, you are right. With the pot omxplayer your _hole_ is 100% working.
